Lab 1
Sreya Sunil Kurup
AM.EN.U4AIE20068

In [ ]:
import numpy as np

**Creating Array in Numpy**

In [ ]:
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


**Python list to a numpy array**

In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list##array

array([1, 9, 8, 3])

In [ ]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [ ]:
##Add 10 to each number in list
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


**Shape of Array**


In [ ]:
a  = np.array([1,2,3])
print(a.shape)#dimension
print(a.dtype)

(3,)
int64


In [ ]:
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

**numpy.zeros()**


In [1]:
import numpy as np
x=np.zeros((4,4), dtype=np.int16)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)	

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

**Reshape Data**


In [ ]:
##Change dimensions
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

**Flatten Data**


In [ ]:
e.flatten()


array([1, 2, 3, 4, 5, 6])

**What is hstack?**

In [ ]:
## append into horitzontal stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


**What is vstack?**


In [ ]:
## append into Vertical stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


**Generate Random Numbers**

In [ ]:
## Generate random number from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)			

[4.7132515  4.99456695 5.39501285 5.73161337 5.12783294 4.77528625
 5.78166696 6.04191642 5.35743039 4.86151302]


**Asarray**
 

In [ ]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


**numpy.arange()?**


In [ ]:
np.arange(1, 11)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 14, 4)	

array([ 1,  5,  9, 13])

**Linspace**


In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

**LogSpace**

In [ ]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

**Indexing and slicing**

In [ ]:
## Slice
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)


[[1 2 3]
 [4 5 6]]


In [ ]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [ ]:
print('Second column:', e[:,1])	

Second column: [2 5]


In [ ]:
## Second Row, two values
print(e[1, :2])

[4 5]


In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[5.38157118 5.37186171 5.05123951 4.32336104 4.66653566 5.81183913
 4.63195366 5.2945789  5.55464569 5.5953062 ]


In [ ]:
### Find Min 
print(np.min(normal_array))

### Find Max 
print(np.max(normal_array))

### Find Mean 
print(np.mean(normal_array))

###Find  Median
print(np.median(normal_array))

### Find Sd
print(np.std(normal_array))

4.71325150012944
6.041916418348529
5.278009064226401
5.242631664952149
0.4371524701886887


**What is numpy dot product?**


In [ ]:
### Dot product
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

**Matrix Multiplication**


In [ ]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

**Inverse**

In [ ]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# inverse
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


**Determinant**

In [ ]:
n_array = np.array([[50, 29], [30, 44]])
  
print("Numpy Matrix is:")
print(n_array)
  
###determinant
det = np.linalg.det(n_array)
  
print("\nDeterminant of given matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given matrix:
1330


**Rank of a Matrix**

In [ ]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# rank
np.linalg.matrix_rank(mx)

3

**Eigenvectors And Eigenvalues**

In [ ]:
matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


**Get diagonal of a matrix**

In [ ]:
gfg = np.matrix('[6, 2; 3, 4]')
         
# Diagonal
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


**Matrix transpose**

In [ ]:
gfg = np.matrix('[4, 1; 12, 3]')
              
# transpose()
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


**Trace of a matrix**

In [ ]:
gfg = np.matrix('[4, 1; 12, 3]')
              
# trace()
tracem = gfg.trace()
    
print(tracem)

[[7]]
